apiVersion: v1
kind: BuildConfig
metadata:
  name: hello-service-bc
  labels:
    app: hello
spec:
  output:
    to:
      kind: ImageStreamTag
      name: hello-service-is:initial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy:
    type: Docker
